### ISSUE TITLE
Can't build rpma on ubuntu 16

### ISSUE THREAD

**Issue by GrayXu** [pmem/rpma#1138]
I cloned codes in the master branch and tried to build them on ubuntu 16, but encountered some errors.

```
cmake ..

-- Checking for module 'libibverbs'
--   No package 'libibverbs' found
-- Checking for module 'libibverbs' w/o PkgConfig
--   Found libibverbs w/o PkgConfig
-- Checking for module 'librdmacm'
--   No package 'librdmacm' found
-- Checking for module 'librdmacm' w/o PkgConfig
--   Found librdmacm w/o PkgConfig
-- Checking for module 'libpmem>=1.6'
--   No package 'libpmem' found
-- On-Demand Paging (ODP) in libibverbs supported - Success
-- Using a new signature of rdma_getaddrinfo()
CMake Warning at tests/CMakeLists.txt:31 (message):


  WARNING: The RPMA_SOFT_ROCE_IP environment variable is not set! It should
  contain an IP address of a SoftRoCE-configured network interface.

  127.0.0.1 will be used instead, the tests requiring SoftRoCE can fail!

  There are possible two alternative actions:

  a) Run 'make config_softroce' to configure SoftRoCE and to get the IP of a
  SoftRoCE-configured network interface and set the RPMA_SOFT_ROCE_IP
  environment variable to silent this message.

  or:

  b) Set the TESTS_SOFT_ROCE cmake variable to OFF in order to disable tests
  that require a SoftRoCE-configured network interface.


-- Checking for executable 'pylint'
--   Found pylint
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gray/PMDK/pmdk/rpma/cmake
```

```
make  # remake

[  0%] Built target checkers
[  2%] Built target rpma
[  2%] Built target test_backtrace
[  2%] Building C object tests/unit/conn/CMakeFiles/conn-flush.dir/__/common/mocks-rdma_cm.c.o
/home/gray/PMDK/pmdk/rpma/tests/unit/common/mocks-rdma_cm.c:303:1: error: conflicting types for ‘rdma_getaddrinfo’
 rdma_getaddrinfo(const char *node, const char *port,
 ^~~~~~~~~~~~~~~~
In file included from /home/gray/PMDK/pmdk/rpma/tests/unit/common/mocks-rdma_cm.c:8:0:
/usr/include/rdma/rdma_cma.h:706:5: note: previous declaration of ‘rdma_getaddrinfo’ was here
 int rdma_getaddrinfo(char *node, char *service,
     ^~~~~~~~~~~~~~~~
tests/unit/conn/CMakeFiles/conn-flush.dir/build.make:117: recipe for target 'tests/unit/conn/CMakeFiles/conn-flush.dir/__/common/mocks-rdma_cm.c.o' failed
make[2]: *** [tests/unit/conn/CMakeFiles/conn-flush.dir/__/common/mocks-rdma_cm.c.o] Error 1
CMakeFiles/Makefile2:1446: recipe for target 'tests/unit/conn/CMakeFiles/conn-flush.dir/all' failed
make[1]: *** [tests/unit/conn/CMakeFiles/conn-flush.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

thx!

**Comment by yangx-jy** [comment]
Hi @GrayXu 

I think you try to build rpma by the default c compiler (i.e. "cc").
For the "cc" compiler, current rpma cannot check the version of `rdma_getaddrinfo()` correctly.

For now, you can avoid the issue by using the "gcc" compiler:
```
CC=gcc cmake ..
make
```

BTW: I also have sent a patch (#1139 ) to fix the issue.

Best Regards,
Xiao Yang

**Comment by janekmi** [comment]
Hi @GrayXu. We have just merged the fix for the issue you have found. Please let us know if it solves the issue completely.
Thank you @yangx-jy for stepping in. 👍

**Comment by janekmi** [comment]
Hope it helps. Please reopen if needed. Cheers!

**Comment by GrayXu** [comment]
Thanks for your reply!
But here `cc` is just an alias of `gcc`...
```
$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~16.04)
```

And I still can't build it correctly with the latest codes. The error during cmake indicates that it can't find **"LIBIBVERBS"**.

error log:
```
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Perl: /usr/bin/perl (found version "5.22.1")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:35 (include):
  include could not find requested file:

    /home/gray/PMDK/pmdk/rpma/cmake/functions.cmake


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'libibverbs'
--   No package 'libibverbs' found
CMake Error at CMakeLists.txt:97 (find_package):
  By not providing "FindLIBIBVERBS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LIBIBVERBS", but CMake did not find one.

  Could not find a package configuration file provided by "LIBIBVERBS" with
  any of the following names:

    LIBIBVERBSConfig.cmake
    libibverbs-config.cmake

  Add the installation prefix of "LIBIBVERBS" to CMAKE_PREFIX_PATH or set
  "LIBIBVERBS_DIR" to a directory containing one of the above files.  If
  "LIBIBVERBS" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/gray/PMDK/pmdk/rpma/build/CMakeFiles/CMakeOutput.log".
See also "/home/gray/PMDK/pmdk/rpma/build/CMakeFiles/CMakeError.log".
```

here is the version of libibverbs-dev, I installed them by `apt`. Is it an error caused by different versions (too old)?
```
libibverbs-dev/now 41mlnx1-OFED.4.9.0.0.7.49224 amd64 [installed,local]
libibverbs1/now 41mlnx1-OFED.4.9.0.0.7.49224 amd64 [installed,local]
libibverbs1-dbg/now 41mlnx1-OFED.4.9.0.0.7.49224 amd64 [installed,local]
```

Thanks again!

**Comment by GrayXu** [comment]
I correct my dependence lib versions, and now I can build rpma.

But still some warnings during cmake. 

```
-- Checking for module 'libpmem>=1.6'
--   No package 'libpmem' found
CMake Warning at CMakeLists.txt:107 (message):
  Since libpmem is missing, the examples will be unable to use PMem.  They
  will be using DRAM instead.
```

Because of no libpmem apt source. I built and installed the lastest release (1.11.0) of libpmem from source codes. But the info above shows that it can't find libpmem...

Confusing...

---

btw, I can't open an issue closed by contributors

**Comment by GrayXu** [comment]
Thanks for your help, I've already [fixed this `build error` problem.](https://github.com/pmem/rpma/issues/1138#issuecomment-917950309)  
And I create [another issue](https://github.com/pmem/rpma/issues/1286) for [`can't find libpmem` problem](https://github.com/pmem/rpma/issues/1138#issuecomment-917950309)

Thanks again
